### ISSUE TITLE
docs: update readme

### ISSUE THREAD

**Issue by vince-fugnitto** [vince-fugnitto/vscode-juve#1]
#### Description

The readme is currently the auto-generated one, and should ultimately be updated to describe and provide details about the extension.

**Comment by Jay179-sudo** [comment]
Hi! May I work on this issue? I'm fairly new to open source.

**Comment by vince-fugnitto** [comment]
> Hi! May I work on this issue? I'm fairly new to open source.

I forgot to close the issue with https://github.com/vince-fugnitto/vscode-juve/pull/8, is there something else you might want to work on? For example, a new command that may point to an interesting link.
